SET CACHE_SIZE 16384;
SET TRACE_LEVEL_SYSTEM_OUT 0;
SET DEFAULT_TABLE_TYPE 0;
SET CLUSTER '';
SET DEFAULT_LOCK_TIMEOUT 1000;
SET WRITE_DELAY 500;
SET TRACE_LEVEL_FILE 1;
;

-- USERS
CREATE USER IF NOT EXISTS SA
  SALT '6a0e04afeac6bccc' HASH '065c94fe8fb12546403bd50ab883a59cd664b25ceb9f7bd8a1420a74099d0d3b' ADMIN;

-- SEQUENCE
CREATE SEQUENCE USER_SEQ INCREMENT BY 1;
CREATE SEQUENCE CAPITAL_SEQ INCREMENT BY 1;
CREATE SEQUENCE COUNTRY_SEQ INCREMENT BY 1;

-- TABLES
CREATE CACHED TABLE PUBLIC.USER (
  ID INT NOT NULL DEFAULT nextval('USER_SEQ') PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(50) NOT NULL,
  ENABLED  BOOLEAN     NOT NULL,
  ROLE     VARCHAR(20) NOT NULL
);

CREATE CACHED TABLE PUBLIC.CAPITAL (
  ID INT NOT NULL DEFAULT nextval('CAPITAL_SEQ') PRIMARY KEY,
  NAME       VARCHAR(50) NOT NULL UNIQUE,
  POPULATION INT
);

CREATE CACHED TABLE PUBLIC.COUNTRY (
  ID INT NOT NULL DEFAULT nextval('COUNTRY_SEQ') PRIMARY KEY,
  NAME       VARCHAR(50) NOT NULL UNIQUE,
  CAPITAL    VARCHAR(50),
  AREA       INT,
  POPULATION INT,
  CURRENCY   VARCHAR(3),
  FOREIGN KEY (CAPITAL) REFERENCES CAPITAL(NAME)
);