-- USER TABLE
INSERT INTO PUBLIC.USER(ID, USERNAME, PASSWORD, ROLE) VALUES(1, 'admin', 'admin', 'user');

-- COUNTRY TABLE
INSERT INTO PUBLIC.COUNTRY(NAME, CAPITAL, AREA, POPULATION, CURRENCY) VALUES('Poland', 'Warsaw', 312685, 38000000, 'PLN');
INSERT INTO PUBLIC.COUNTRY(NAME, CAPITAL, AREA, POPULATION, CURRENCY) VALUES('Germany', 'Berlin', 357340, 81000000, 'EUR');
INSERT INTO PUBLIC.COUNTRY(NAME, CAPITAL, AREA, POPULATION, CURRENCY) VALUES('UK', 'London', 244820, 63000000, 'GBP');